# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170412_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='storeName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verifiedStore',
        ),
    ]
