# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170319_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=3.0),
        ),
    ]
