# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170319_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storeName',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='verifiedStore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
    ]
