# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170319_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='storeName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
