# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayName',
            field=models.CharField(default='hellonuts', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
