# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_displayname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='displayName',
        ),
    ]
