# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170319_1623'),
        ('store', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionRating', models.FloatField()),
                ('conditionDescription', models.TextField()),
                ('status', models.TextField()),
                ('isTeared', models.BooleanField()),
                ('isStained', models.BooleanField()),
                ('location', models.TextField()),
                ('price', models.BooleanField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SubCatergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='owner',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='avgPrice',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='highestCurrListing',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='highestHistListing',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lowestCurrListing',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lowestHistLising',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subCatergory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.SubCatergory'),
            preserve_default=False,
        ),
    ]
