# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountExchanged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deliveryAddress', models.TextField()),
                ('receiveAddress', models.TextField()),
                ('timeSold', models.DateTimeField(auto_now=True)),
                ('ratingSeller', models.DecimalField(decimal_places=1, max_digits=1)),
                ('ratingBuyer', models.DecimalField(decimal_places=1, max_digits=1)),
                ('isValid', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Listing', to='shop.Listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='seller',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='available',
            new_name='viisible',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
