# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170807_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
    ]
