# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170721_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCatergory',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subCatergory',
            new_name='subCategory',
        ),
    ]
