# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170807_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lowestSoldLising',
            new_name='lowestSoldListing',
        ),
    ]
