# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170706_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
