# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Listings'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='avgSoldPrice',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='highestCurrListing',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='highestSoldListing',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='lowestCurrListing',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='lowestSoldLising',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lisiting', to='shop.Item'),
        ),
        migrations.AlterIndexTogether(
            name='listing',
            index_together=set([('id',)]),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
