# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 04:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(default='', max_length=40)),
                ('bio', models.TextField(null=True)),
                ('rating', models.FloatField(default=3.0, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                ('verifiedStore', models.BooleanField(default=False)),
                ('storeName', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
