# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0004_auto_20170626_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hi', max_length=30, verbose_name='username'),
            preserve_default=False,
        ),
    ]
