# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='isStained',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isTeared',
        ),
    ]
