# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_listing_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
